CREATE DATABASE IF NOT EXISTS BSM;
USE BSM;

CREATE TABLE IF NOT EXISTS Categories (
	PK_CategoryId INT AUTO_INCREMENT,
    CategoryName VARCHAR(45) NOT NULL,
    CONSTRAINT PK_CategoryId PRIMARY KEY (PK_CategoryId)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS Purchases (
	PK_PurchaseId INT AUTO_INCREMENT,
    FK_CategoryId INT, 
    Cost DECIMAL(13,2) NULL,
    Date Date NOT NULL,
    CONSTRAINT PK_PurchaseId PRIMARY KEY (PK_PurchaseId),
    CONSTRAINT FK_Purchases_CategoryId FOREIGN KEY (FK_CategoryId) REFERENCES Categories (PK_CategoryId)
) ENGINE=INNODB;